---
ID: "4a8a4e8c-9680-45f7-ab2b-4a85af2fc2c6"
Parent: "fc42a176-a809-4750-8512-eff5dcf06c68"
Template: "fc42a176-a809-4750-8512-eff5dcf06c68"
Path: /sitecore/templates/TheAA/Presentation/RepresentativeExampleSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211028T071454Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f189873c-460d-4cda-a482-7ded009f86b9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211111T043519Z
