---
ID: "f0cbe920-8cb9-43c0-a002-64c70c17f537"
Parent: "76fc3a21-1189-496c-9883-1a65cf4d5f01"
Template: "504aa82f-628e-462b-b5ed-305056c002d5"
Path: "/sitecore/content/AA/mobile-app/mobile-app/components/notifications/service"
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{8500EC05-BF8F-468E-BC0D-95C9EAFC61A8}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240812T083133Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{9CC7509E-B91B-4694-9A8F-AC84BBF84E8D}"
    - ID: "45c8f87d-a9e7-45f9-83ac-012d5db3bec7"
      Hint: Description
      Value: "Your vehicle {{VRN}} is due for servicing in {{xx}} days"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "7de06c4c-4454-44ae-8c90-5217ce552f12"
      Hint: Title
      Value: The AA
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1460b3e4-0dd7-405c-9936-e0949cf4be47"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Simple.Jain
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241104T060915Z
    - ID: "e3b2908b-0e00-4ea7-9a22-47c0cc2a0645"
      Hint: Type
      Value: "{53C507B8-475A-4C53-A736-BEE025ECE85B}"
    - ID: "e8062922-d7ad-4a29-a859-f6bb460dc568"
      Hint: Deeplink
      Value: "theaa://com.theaa.theaa/p/v?Reg={{VRN}}"
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241128T111758Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{9CC7509E-B91B-4694-9A8F-AC84BBF84E8D}"
    - ID: "45c8f87d-a9e7-45f9-83ac-012d5db3bec7"
      Hint: Description
      Value: "Book {{VRN}} in for a service at an AA-approved garage."
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Machelia.Williams
    - ID: "7de06c4c-4454-44ae-8c90-5217ce552f12"
      Hint: Title
      Value: "Service due in {{xx}} days"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f12cc53a-7eb8-4a9d-9d8c-bfaad65620c4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Machelia.Williams
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20241128T111758Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241128T111825Z
    - ID: "e3b2908b-0e00-4ea7-9a22-47c0cc2a0645"
      Hint: Type
      Value: "{53C507B8-475A-4C53-A736-BEE025ECE85B}"
    - ID: "e8062922-d7ad-4a29-a859-f6bb460dc568"
      Hint: Deeplink
      Value: "theaa://com.theaa.theaa/p/v?Reg={{VRN}}"
  - Version: 3
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241205T111444Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{9CC7509E-B91B-4694-9A8F-AC84BBF84E8D}"
    - ID: "45c8f87d-a9e7-45f9-83ac-012d5db3bec7"
      Hint: Description
      Value: "Your service for {{VRN}} is due in {{xx}} days - book in at an AA-approved garage."
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Machelia.Williams
    - ID: "7de06c4c-4454-44ae-8c90-5217ce552f12"
      Hint: Title
      Value: The AA
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "28a8adc6-7551-4bfe-aece-85772cf3c745"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Machelia.Williams
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20241205T111444Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241205T112643Z
    - ID: "e3b2908b-0e00-4ea7-9a22-47c0cc2a0645"
      Hint: Type
      Value: "{53C507B8-475A-4C53-A736-BEE025ECE85B}"
    - ID: "e8062922-d7ad-4a29-a859-f6bb460dc568"
      Hint: Deeplink
      Value: "theaa://com.theaa.theaa/p/v?Reg={{VRN}}"
  - Version: 4
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241205T112700Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{9CC7509E-B91B-4694-9A8F-AC84BBF84E8D}"
    - ID: "45c8f87d-a9e7-45f9-83ac-012d5db3bec7"
      Hint: Description
      Value: "Your service for {{VRN}} is due in {{xx}} days. Book in at an AA-approved garage near you."
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Machelia.Williams
    - ID: "7de06c4c-4454-44ae-8c90-5217ce552f12"
      Hint: Title
      Value: The AA
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "25b048aa-efd0-4834-88a2-991c4b56702d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Machelia.Williams
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20241205T112700Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241205T112731Z
    - ID: "e3b2908b-0e00-4ea7-9a22-47c0cc2a0645"
      Hint: Type
      Value: "{53C507B8-475A-4C53-A736-BEE025ECE85B}"
    - ID: "e8062922-d7ad-4a29-a859-f6bb460dc568"
      Hint: Deeplink
      Value: "theaa://com.theaa.theaa/p/v?Reg={{VRN}}"
  - Version: 5
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241205T112828Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{9CC7509E-B91B-4694-9A8F-AC84BBF84E8D}"
    - ID: "45c8f87d-a9e7-45f9-83ac-012d5db3bec7"
      Hint: Description
      Value: "Your service for {{VRN}} is due in {{xx}} days. Book in at an AA-approved garage near you."
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Machelia.Williams
    - ID: "7de06c4c-4454-44ae-8c90-5217ce552f12"
      Hint: Title
      Value: The AA
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "225496ca-7c40-429e-a78f-4a2bee1924ef"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Machelia.Williams
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20241205T112828Z
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241205T112906Z
    - ID: "e3b2908b-0e00-4ea7-9a22-47c0cc2a0645"
      Hint: Type
      Value: "{53C507B8-475A-4C53-A736-BEE025ECE85B}"
    - ID: "e8062922-d7ad-4a29-a859-f6bb460dc568"
      Hint: Deeplink
      Value: "theaa://com.theaa.theaa/p/v?Reg={{VRN}}"
