---
ID: "d99fea2b-000d-4cb0-8c83-75de2085ca03"
Parent: "ae510c7b-f87d-4de5-b748-2e6b3efb16b2"
Template: "ae510c7b-f87d-4de5-b748-2e6b3efb16b2"
Path: /sitecore/templates/Foundation/Presentation/ImageBorderRadiusSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240307T061650Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4a6a73fa-2db5-41e0-8ad2-2a1fc629ccae"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240829T015633Z
