---
ID: "c8a107a9-b3e6-4dbb-a552-88b82143d89c"
Parent: "6ec8244f-ccd8-4a4b-b8f4-f94bd0dfa293"
Template: "6ec8244f-ccd8-4a4b-b8f4-f94bd0dfa293"
Path: /sitecore/templates/TheAA/Modules/PersonalOrVehicle/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211222T132522Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "78a56110-f897-434e-ab5d-0e3386b7f9d2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220120T043909Z
