---
ID: "73fa44ac-5154-4ae3-88bf-c72f63535ee3"
Parent: "2f4f8581-2864-4611-beca-a3226f52ebc7"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/TheAA/Modules/LoanDataCaptureValues/Loan Data Capture Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181115T100132Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "61be44ce-daa8-4424-9d86-e3d9364ccd4a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190627T063823Z
