---
ID: "7c973ccb-116f-4e7a-b33c-af235b4d68b9"
Parent: "9ae3af6a-f46c-49ad-89b0-867f9b17c767"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/TheAA/Presentation/CampaignSettings/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160203T160204Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8eedb1d4-052b-486a-bb2a-cbd79bd90e55"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160203T160431Z
