---
ID: "6130b6de-b02d-4663-88ac-57e340a934dd"
Parent: "a95effb4-0c79-480a-a05d-9be77745848d"
Template: "a95effb4-0c79-480a-a05d-9be77745848d"
Path: /sitecore/templates/Foundation/AA/Presentation/ImageAlignmentSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240307T061650Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "25d2fd52-2e61-4bde-9f91-bd0b213acc13"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240829T015634Z
