---
ID: "debfc97b-c409-4234-ba39-6f69440f434e"
Parent: "a1dffee5-3b3a-49c1-a2c1-e073bb954348"
Template: "a1dffee5-3b3a-49c1-a2c1-e073bb954348"
Path: /sitecore/templates/TheAA/Modules/BalanceTransferCalculator/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "21c4aaa7-c2fa-4890-bdce-73c26b89418f"
      Hint: BalanceFieldIsInvalid
      Value: What's the balance on this card
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160805T144540Z
    - ID: "4e0cebb6-863a-4e81-bf19-d40edfe9e958"
      Hint: AddAnotherCardSubText
      Value: (max of 6 cards)
    - ID: "548cfcab-3afa-4703-a027-59b17f63921b"
      Hint: InterestRateFieldIsInvalid
      Value: What's the interest rate on this card
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "69fb3ff4-72dd-4d70-abfb-340b689dbd93"
      Hint: BalanceText
      Value: Balance
    - ID: "724fc5d9-b6b1-4312-8815-d5572a61f62c"
      Hint: InterestRateText
      Value: Interest Rate
    - ID: "8292486e-16b5-4d50-96fb-8d17fe751948"
      Hint: CalculateButtonText
      Value: Calculate
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "31da20de-6523-4c89-a053-90e45a8f6a37"
    - ID: "998594b3-1bec-4f90-88a1-a9845ec16a35"
      Hint: AddAnotherCardText
      Value: Add another card
    - ID: "ba9dd1f0-5780-49a4-9630-a4ee4b0d2e6d"
      Hint: TotalAmountText
      Value: "You could save:"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160805T144656Z
