---
ID: "3a10bcd1-7ea3-4434-9553-fcaf79967b9a"
Parent: "27ee3c8f-a0be-4720-8cf6-88ea4b0f39a8"
Template: "27ee3c8f-a0be-4720-8cf6-88ea4b0f39a8"
Path: /sitecore/templates/Feature/AA/Product Builder/CoreProduct/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160603T143111Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "630c85d8-33b4-48a8-b135-5b9a7245104b"
      Hint: ProductName
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "34379f9a-289e-4245-b35b-1bab9f38935d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220203T044035Z
