---
ID: "a16532e7-eb23-4e17-9808-91aa52c3cbfa"
Parent: "7e237bd6-fd52-4309-b6f4-42019f4f4dfa"
Template: "7e237bd6-fd52-4309-b6f4-42019f4f4dfa"
Path: /sitecore/templates/Feature/AA/Basic Content/Skinny Banner/Skinny Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241210T112620Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0e370f01-2bbc-407a-9647-081cd49b84cc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250116T004721Z
