---
ID: "4fcad2b0-1a35-4198-a974-1cce2801deb7"
Parent: "24bb1d84-5fbd-4d3e-9899-2b04cbcc8fd5"
Template: "24bb1d84-5fbd-4d3e-9899-2b04cbcc8fd5"
Path: /sitecore/templates/TheAA/Settings/SalesJourney/Blocks/FstOfferType/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160909T111654Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f940c39d-de1b-4b29-a14b-15756aa6f740"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180913T084410Z
