---
ID: "464f866e-da2d-4e9c-bad3-31f2be912899"
Parent: "d1619ade-0cbf-4fb3-bacb-fc80bd3a66f8"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/TheAA/Settings/LoanDataCaptureConfiguration/Loan Data Capture Configuration/LoanCalculatorUrlConfigurations
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: "query:/sitecore/content/TheAA/Modules/Loan Calculator//*[@@templateid='{3A472BD6-D291-4A9D-9451-235E821FBC70}']"
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Droplink
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1100
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: Loan calculator url configurations
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181120T133320Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "690b44fa-6a93-441b-981e-a17b69217a20"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210505T072103Z
