---
ID: "53960ec8-ae23-4ee0-84ee-30993134583f"
Parent: "26e1c8f8-6c5f-41fd-842d-a29f3c8db3b4"
Template: "26e1c8f8-6c5f-41fd-842d-a29f3c8db3b4"
Path: /sitecore/templates/TheAA/Modules/SubstantiationBlock/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160302T154324Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2cee0182-074c-48b5-b6e9-7c8c087a67e5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220120T043909Z
