---
ID: "9cab7179-aa9c-4b25-a25d-b95e92b86b5c"
Parent: "a2835f66-ff81-4525-aefd-6876ac4bec2c"
Template: "a2835f66-ff81-4525-aefd-6876ac4bec2c"
Path: /sitecore/templates/TheAA/Settings/Hospitality/Award/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1fc90c06-3cbe-4bed-af63-12fb8b6b5b49"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160817T153126Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "40d8edbc-56cb-45bf-98c5-1e49b131e8c7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160817T153141Z
