---
ID: "9b127366-d0cf-41e4-9923-d6dd980a25c7"
Parent: "24ebbd31-47db-49b0-ba59-1c9bfab3505e"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/TheAA/Settings/SalesJourney/Promos/SalesJourneyLozengeItem/Sales Journey Lozenge Item/ProductCode
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Single-Line Text"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220622T103812Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mitab
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b06152b9-06c4-4556-b6ce-8545bc6ac131"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220714T033433Z
