---
ID: "ccc030d4-90a6-412a-a4c9-d5160306055d"
Parent: "9065996f-b497-469e-bde2-4636f9aa2aa3"
Template: "9065996f-b497-469e-bde2-4636f9aa2aa3"
Path: /sitecore/templates/Foundation/Presentation/ImageSizeSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240307T061650Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b1001aaa-851e-4e4f-af96-b9583523c6b1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240829T015634Z
