---
ID: "d1619ade-0cbf-4fb3-bacb-fc80bd3a66f8"
Parent: "97f36b69-cac8-469a-9d49-85afc657e119"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/TheAA/Settings/LoanDataCaptureConfiguration/Loan Data Capture Configuration
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181116T100022Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a71aa0ef-1dd0-4b2a-a97a-3f157ca94da4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210505T072103Z
