---
ID: "7084de58-b498-4d69-9a9b-2e2a0bf85114"
Parent: "a6fd4b54-a5b6-412a-afd4-7cac7392728f"
Template: "a6fd4b54-a5b6-412a-afd4-7cac7392728f"
Path: /sitecore/templates/TheAA/Modules/DrivingSchoolLocationPage/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "06bd152e-e90a-47f5-979f-9b3000942f52"
      Hint: AreaCovered
      Value: |
        <h2>Where do AA Driving School offer driving lessons in Location.name?</h2>
        <li><strong>North</strong>: Barnet, Southgate, Enfield, Haringey, Arsenal, Finsbury Park, Finchley, Camden...</li>
        <li><strong>East</strong>: Barking and Dagenham, Bexley, Greenwich, Hackney, Havering, Lewisham, Newham, Redbridge, Tower Hamlets, Waltham Forest...</li>
        <li><strong>South East</strong>: Lewisham, Forest Hill, Bromley, Denmark Hill, Brockley, Sydenham, Crystal Palace, Nunhead...</li>
        <li><strong>South</strong>: Clapham, Tooting, Balham, Vauxhall, Brixton, Herne Hill...</li>
        <li><strong>South West</strong>: Richmond, Wimbledon, Hounslow, Perivale, Fulham, Putney...</li>
        <li><strong>West</strong>: Hammersmith, Shepherds Bush, Ealing, White City, Acton...</li>
        <li><strong>North West</strong>: Kensal Rise, Marylebone, Golders Green, Dollis Hill, Wembley, Harrow, Watford...</li>
        <li><strong>North West</strong>: Kensal Rise, Marylebone, Golders Green, Dollis Hill, Wembley, Harrow, Watford...</li>
    - ID: "13a906ba-eaa6-4dcb-8021-ebe4bd37e89f"
      Hint: TipsAndTricks
      Value: |
        <h2>Tips and tricks from our instructors</h2>
        <p>"It's easy to feel daunted when you first learn to drive but the best advice I'd give anyone is to be kind to yourself - there's a point when everything falls into place, and it all starts to make sense. Trust me on that. Secondly, always keep an eye on what's going on around you, even if you think the road is clear - take those few extra seconds to check." - John, AA Driving Instructor from Forest Hill in London</p>
    - ID: "1e476685-94ed-4304-8d47-acfbb07f15aa"
      Hint: LocationSharedContentReference
      Value: "{49A0E860-A525-4B15-BF37-8DD90E265C29}"
    - ID: "203f5cc6-98e3-4d21-a39b-f1d00a712ccb"
      Hint: TestCenters
      Value: |
        <style>
            .column {
            float: left;
            width: 24%;
            }
            /* Clear floats after the columns */
            .row:after {
            content: "";
            display: table;
            clear: both;
            }
        </style>
        <h2>Taking your driving test in Location.name</h2>
        <p>There are 28 driving test centres in Location.name - so you're spoiled for choice. You can find your closest one in the list below.</p>
        <table style="width:100%;">
            <tbody>
                <tr>
                    <td style="width:25%;"><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a><br />
                    </td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a><br />
                    </td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a><br />
                    </td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a><br />
                    </td>
                </tr>
                <tr>
                    <td style="width:25%;"><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                </tr>
                <tr>
                    <td style="width:25%;"><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                </tr>
                <tr>
                    <td style="width:25%;"><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                    <td><a href="https://urldefense.proofpoint.com/v2/url?u=http-3A__www.dft.gov.uk_fyn_practical.php-3Fpostcode-3DSE13-2B6JD-26testtype-3DAll&amp;d=DwMG-g&amp;c=7HXQkpfw9RhjnklpS1w2AQ&amp;r=bBXyTt-s1dS3wd5KY95ycTCIYm_AIjNbvOhA2-Hywmw&amp;m=6ezFRxFquda3QTnixUde0udyHZh1sRKheWYbChoV5k8&amp;s=9GFoIAWZxriEHTis4VLlH7YdiqFlSt8ViHgqFQISG0Y&amp;e=" target="_blank">Hither Green</a></td>
                </tr>
            </tbody>
        </table>
        <br />
        <p>xx% of learner drivers in Location.name passed their test first time thanks to AA Driving School.<br />
        From the first time behind the wheel, to test day - we'll guide you to success.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190125T132217Z
    - ID: "3be27b48-73e1-43c2-bf0f-0fef4b4e9a50"
      Hint: ReviewsAndTestimonial
      Value: "{D3B558A2-C5C3-4276-BEE9-B5F6F0682E41}"
    - ID: "538e208c-fde5-4221-a14f-f027c8e168eb"
      Hint: LocationName
      Value: New London
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f1ef69e7-7c49-44aa-baee-4ccac7848510"
    - ID: "9fe96ae5-09c9-4580-bec8-d583a7a1f50f"
      Hint: IntroParagraph
      Value: |
        <p>Location.name is one of the most exciting cities on the planet - so why spend most of your time underground? Learning to drive and navigate around the UK's capital will open up so much more of the city to you. Say farewell to cramped tube trains and busy buses - from now on, it's just you and your car taking on the road together.</p>
        
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190402T042604Z
