---
ID: "5e2fcbf1-8e21-4dd9-932f-bafac7d97f3e"
Parent: "26a4e690-1553-41c1-895a-d7119ff1bb0e"
Template: "7f7a3339-d823-4556-9814-42c3dbd68c7a"
Path: /sitecore/system/Settings/Buckets/Settings/Quick Actions/Configure Standard Values
SharedFields:
- ID: "cd521d55-cfd4-447a-b386-8fc9f122b01e"
  Hint: Command
  Value: "template:launchstandardvalues"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120920T161600
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0375e923-3dfa-47e8-ba6e-0fdf715c7816"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20130125T093321:634947032014154044"
