---
ID: "e6371145-88c9-438c-b5fa-7a8cfb4cc7e7"
Parent: "4debfbf1-d63c-465d-b105-d4b548e47c5e"
Template: "4debfbf1-d63c-465d-b105-d4b548e47c5e"
Path: /sitecore/templates/Feature/AA/Structure/Columns/ParametersTemplate_ColumnWidth/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "22ce8fe0-bac5-449e-9eb9-cae5bb8d3f57"
      Hint: Number of column
      Value: "{42AE8520-8E67-433F-91D2-456370B1B5FF}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211125T131102Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c6c749c5-6c31-4592-9bfa-0375364e949d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220120T043921Z
