---
ID: "d55c1e5f-b7d5-4501-b638-e59a241e8f10"
Parent: "d02fa491-7f14-49be-93b2-bcb6790d17ae"
Template: "d02fa491-7f14-49be-93b2-bcb6790d17ae"
Path: /sitecore/templates/Feature/AA/LandingPage/RPT_HeroBannerSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240722T075750Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aa344fe4-b286-486f-8d94-4eaf8d809676"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240829T015629Z
