---
ID: "eaa6cd6b-ae31-494f-8de5-1ad162f007e6"
Parent: "6eac978c-32ea-42eb-9875-dff9e243c2b5"
Template: "f0d16eee-3a05-4e43-a082-795a32b873c0"
Path: /sitecore/system/Settings/Rules/Definitions/Elements/Workflows/Workflow
SharedFields:
- ID: "ab51c8b2-f0e1-4471-9aae-cc080d774923"
  Hint: Type
  Value: Sitecore.Rules.Conditions.WorkflowConditions.WorkflowCondition,Sitecore.Kernel
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20080923T083900
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dcaabcaa-9934-40b4-bd8b-d606557eee7c"
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "where the item is in the [workflowid,Tree,root={05592656-56D7-4D85-AACF-30919EE494F9}&selection=System/Workflow/Workflow,specific] workflow"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: "20121002T122718:634847776380268505"
