---
ID: "54e527d5-b69d-49d6-897b-2cfebafde97c"
Parent: "6bb6c84e-60a1-4748-b63b-86b2a0158f1a"
Template: "6bb6c84e-60a1-4748-b63b-86b2a0158f1a"
Path: /sitecore/templates/Foundation/AA/Presentation/LinkStyleSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240307T061650Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0f82af13-3419-47d6-9d48-0e5d754a2f8e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241001T014821Z
