---
ID: "0c4ed4f5-51b7-4746-99d5-8b1708254f61"
Parent: "66e83f69-0607-4179-acac-824cce288ac5"
Template: "66e83f69-0607-4179-acac-824cce288ac5"
Path: /sitecore/templates/TheAA/Modules/IndustryReviews/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/layout_details.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160229T135000Z
    - ID: "471b669a-a426-48ae-a301-ed0fcc18208d"
      Hint: Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bb7aafc4-2234-4a1f-a327-afd4d3ea1a75"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160229T135316Z
