---
ID: "c3af2740-01be-43fc-b615-259ee6ef7f5a"
Parent: "4cfeb389-139d-443b-8a35-0da74b7f33e1"
Template: "4cfeb389-139d-443b-8a35-0da74b7f33e1"
Path: /sitecore/templates/TheAA/Settings/SalesJourney/Step/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160905T154140Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5c4e53d6-05b0-48e7-b528-8ee1a6d34a0b"
    - ID: "a6c71807-d6da-4dfc-9a07-3016a693b92d"
      Hint: IsElementVisibleByDefault
      Value: 1
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160916T122317Z
