---
ID: "39c62404-19a6-416c-a6c9-c23650a7c8b0"
Parent: "dffaee4c-97e1-4a96-9c56-3a58d3e5f078"
Template: "dffaee4c-97e1-4a96-9c56-3a58d3e5f078"
Path: /sitecore/templates/TheAA/Settings/MoxieChatConfiguration/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160201T124815Z
    - ID: "4bce7612-50d4-4b5e-8161-e3b647e8b601"
      Hint: ProviderText
      Value: Live chat by
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "537d3c71-a2e9-44c7-b1fd-6d001be567a0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160201T124834Z
    - ID: "ffe6ca31-4239-462c-8a78-bda7dd6e38ea"
      Hint: ProviderName
      Value: Moxie
