---
ID: "3153c4ed-1b19-4c09-bac5-ee5641e64fa4"
Parent: "0a83ee7b-1f7d-4282-b691-c2b6a1df19d4"
Template: "0a83ee7b-1f7d-4282-b691-c2b6a1df19d4"
Path: /sitecore/templates/Foundation/Presentation/MobileColumnSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240902T054120Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "639a09e4-dca6-4c53-a30a-e85ddfc50e75"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241001T014821Z
