---
ID: "0935b5c1-c375-4261-8b5c-48cce4ab1c6f"
Parent: "70eaf606-ca87-432f-8af9-90b1a2b3ca5d"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/TheAA/Presentation/EligibilityCheckSettings/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160627T153935Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a7e7f0fe-e733-4763-a655-f778eee35cd1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160628T084822Z
