---
ID: "3d0fc8be-f2d7-47f3-b99b-b2b92a7dac16"
Parent: "3b2e4285-683c-4200-b729-31e035b23f42"
Template: "3b2e4285-683c-4200-b729-31e035b23f42"
Path: /sitecore/templates/Feature/Basic Content/Rich Text/Rich Text Plus Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240726T110649Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "09e05c46-90e9-4164-87ed-53ff1ff33aab"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241001T014824Z
