---
ID: "a9721661-602f-4523-8ec7-0b3f40667d33"
Parent: "0b68ce3c-8fd4-4d3f-a45f-a0fbfa1f396e"
Template: "0b68ce3c-8fd4-4d3f-a45f-a0fbfa1f396e"
Path: /sitecore/templates/TheAA/Settings/ProductBuilder/ProductInclusion/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1671e99c-fb34-425e-8bd2-e383631bf62b"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160609T142803Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "52b7cde9-063b-40de-b861-9b78cf70b63e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160609T142810Z
