---
ID: "3e98abd0-4c6f-4e77-ba0e-dd23135cb09a"
Parent: "2f9a5a9b-aaa6-4ade-9b37-b855636adde9"
Template: "2f9a5a9b-aaa6-4ade-9b37-b855636adde9"
Path: "/sitecore/templates/Feature/Headless/Mobile-App/Item Type/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240722T060627Z
    - ID: "702c108c-4099-4722-bc0d-b3efaf6d58ca"
      Hint: Type
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4fd65cfe-18fe-49ef-adfe-241943917569"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250703T015126Z
