---
ID: "17b8be41-cfc8-48ea-a05c-2b60d6768334"
Parent: "4ab05a35-07ed-41ef-9805-5fdc50197e5b"
Template: "4ab05a35-07ed-41ef-9805-5fdc50197e5b"
Path: /sitecore/templates/Foundation/AA/Base Rendering Parameters/ParametersTemplate_ImageSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211217T175839Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dd838b1d-b1cf-48e5-8ff9-ff3b900e409b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220120T043914Z
