---
ID: "aa2e2b95-904d-47ef-b9b8-9e6d57eb99e5"
Parent: "3c521516-bd0e-4ffb-bb1c-44c175cc9a22"
Template: "3c521516-bd0e-4ffb-bb1c-44c175cc9a22"
Path: /sitecore/templates/AllSites/Settings/ContactPointDefinition/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{8500EC05-BF8F-468E-BC0D-95C9EAFC61A8}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160307T144134Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "40665c48-8218-4f94-9dc9-cab0bd8e3192"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160307T144217Z
