---
ID: "31f71bba-8ada-4be8-821a-23f51340f112"
Parent: "d24ab3cd-0963-4e09-9f30-e4fa905a7490"
Template: "d24ab3cd-0963-4e09-9f30-e4fa905a7490"
Path: /sitecore/templates/TheAA/Presentation/DualCtaWithReferrerSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160525T144606Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6036e80e-6f61-4307-878b-7e658f592ecf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250703T015124Z
