---
ID: "02b6cfb7-813b-4268-bf3d-efe22fc15b78"
Parent: "caa886c4-f1ec-4073-93af-6561240c7a66"
Template: "caa886c4-f1ec-4073-93af-6561240c7a66"
Path: /sitecore/templates/Feature/Basic Content/Rich Text/Multi Column Rich Text Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240726T110649Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b6c26419-e812-4fcc-97ea-dcb5ac7ae7a5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240829T015635Z
