---
ID: "d84c0abd-309e-4d4b-b776-d93c65e9fb97"
Parent: "9356ccdc-726b-48b4-8dfb-ebdcafaf7b7d"
Template: "9356ccdc-726b-48b4-8dfb-ebdcafaf7b7d"
Path: /sitecore/templates/Foundation/Folders/Siteroot/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220307T100628Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea116125-827b-47d9-b4a7-f3ad0e828c2a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220317T062120Z
    - ID: "ff3ca58c-810c-49e0-97a5-ec7a3f098285"
      Hint: ShortcutIcon
      Value: |
        <image mediaid="{577FDF7C-0380-46DA-90A4-F2FA2A2E1E31}" />
