---
ID: "d3d56008-b2ea-46f2-b378-14338b11db8d"
Parent: "1d03d106-7acb-4c2f-aa57-36cbd633b4db"
Template: "1d03d106-7acb-4c2f-aa57-36cbd633b4db"
Path: /sitecore/templates/Common/Mobile App Folder/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "688a1df6-9e43-433c-ab71-dad44f9b00f5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240718T014434Z
