---
ID: "050a15bd-04e5-43f2-ac99-f0a4df725793"
Parent: "7524d5ee-91e8-41aa-94c1-136bb46a0c28"
Template: "bed31d6f-d968-45a9-b54e-12d7f977d861"
Path: /sitecore/system/Settings/Foundation/JSS Experience Accelerator/StandardValues/Standard Values Site Setup
SharedFields:
- ID: "06d2c562-9229-4779-8807-e2a5fd2990d4"
  Hint: IsSystemModule
  Value: 0
- ID: "11488836-d40f-40d4-beb4-1d31da7b1470"
  Hint: IncludeByDefault
  Value: 0
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Konfiguration af site med standardværdier
  Versions:
  - Version: 1
    Fields:
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Standardværdier
- Language: "de-DE"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "f814ee65-3acd-47a5-9bcc-804e41cd8321"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "Standardwerte der Website-Einrichtung"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250729T051226Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "952bc4a8-91b6-46eb-84cf-d7e9d279bf1e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Standardwerte
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250729T051226Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181122T001106Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bce6d04b-16fe-4210-a72b-10eda54bfda7"
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Standard Values
- Language: "ja-JP"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "f814ee65-3acd-47a5-9bcc-804e41cd8321"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 標準値のサイト設定
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250729T051226Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "952bc4a8-91b6-46eb-84cf-d7e9d279bf1e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: 標準値
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250729T051226Z
- Language: "zh-CN"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "f814ee65-3acd-47a5-9bcc-804e41cd8321"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 标准值站点设置
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250729T051226Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "952bc4a8-91b6-46eb-84cf-d7e9d279bf1e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: __标准值
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250729T051226Z
