---
ID: "c48d0d34-0222-47a5-8e32-e8c70b3aadb8"
Parent: "af70a11f-125f-4980-8ef6-f124717eb445"
Template: "af70a11f-125f-4980-8ef6-f124717eb445"
Path: /sitecore/templates/Foundation/Settings/LookupValue/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151216T114845Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8645d7e8-ed0b-4de3-aa26-03250635a473"
      Hint: Value
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f2edd67b-77c8-4542-9da2-7aff41b9534a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220120T043914Z
