---
ID: "f7a6315e-c02e-4676-8f8e-312c991cd284"
Parent: "13a428a3-5794-4098-addb-64b4a3b1442f"
Template: "13a428a3-5794-4098-addb-64b4a3b1442f"
Path: /sitecore/templates/TheAA/Presentation/BespokeBackgroundSetting/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190515T092746Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\yadavs
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1051f1a2-f48a-438e-809c-13db77cabe23"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190627T063947Z
    - ID: "f55acc9a-3f11-420d-ae9e-28a8b9ce0f7b"
      Hint: Setting
      Value: "Tiled-repeating-image"
