---
ID: "bcc7354a-5988-4a8f-a259-7b4f9a1d9d86"
Parent: "3be873fe-7d18-423c-beb0-4148dc2ea489"
Template: "3be873fe-7d18-423c-beb0-4148dc2ea489"
Path: /sitecore/templates/Foundation/Base Interface/_ContentWorkflow/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{8500EC05-BF8F-468E-BC0D-95C9EAFC61A8}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160307T141206Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c55e8ef6-2405-4457-8a69-1c85923be4e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220120T043914Z
