---
ID: "df0f0a5a-df26-43f2-b605-e5c11babb05b"
Parent: "8f9c8e2c-7cef-4890-835a-42a06fb27378"
Template: "8f9c8e2c-7cef-4890-835a-42a06fb27378"
Path: /sitecore/templates/TheAA/Modules/ExtrasComponent/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211222T132522Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5bfe018a-e70e-42fb-bcc9-82613bc063ae"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220203T044043Z
