---
ID: "bf136b78-4ef9-4a23-b911-fe2d52e5f6bc"
Parent: "ec0f0570-86b3-467e-831a-8bdff19d9a52"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/TheAA/Modules/ProductLevelCover/Product Level Cover
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190805T084732Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1a3dc52c-d278-401e-87ca-0e867d062c3f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190822T042522Z
