---
ID: "0fa60475-2edd-4ce4-9f29-e385ade5ab56"
Parent: "103813d7-85cb-4933-8dad-673cd66067de"
Template: "103813d7-85cb-4933-8dad-673cd66067de"
Path: /sitecore/templates/TheAA/Modules/HomeContentCalculatorField/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160628T140919Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "92bfa118-53cf-4a96-8cc5-a0b6d11b2ee7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160629T091303Z
    - ID: "f3afbc4d-158f-490e-b4df-f6ae7048863e"
      Hint: Label
      Value: $sentence
