---
ID: "eab943ed-724a-4dd0-9f7e-de7929e304a3"
Parent: "044304ca-33c4-449a-ba8a-bb4363ebafb1"
Template: "044304ca-33c4-449a-ba8a-bb4363ebafb1"
Path: /sitecore/templates/TheAA/Pages/MemberBenefitsCategoryPage/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{BB46309D-349C-4A37-A517-386A917196ED}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181207T092618Z
    - ID: "2e31f721-b2c7-4e9f-88d5-e87d34da261f"
      Hint: RemoveDefaultScripts
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "68195863-8ea6-441c-a82e-a7e0c0d2ad92"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230323T032622Z
