---
ID: "225bff84-784d-43da-98d9-4e29affa6c79"
Parent: "4ed57641-78c1-470e-b734-e3eddb5a5ecf"
Template: "4ed57641-78c1-470e-b734-e3eddb5a5ecf"
Path: /sitecore/templates/Foundation/Presentation/BorderBottomColorSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240307T061650Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "279f5457-badf-4ff5-9d30-d81f1a49b167"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250703T015124Z
