---
ID: "f9ea67cc-e02d-46a1-8089-c86aeb78b7ae"
Parent: "d91d3d2f-9c10-4e6e-9f5c-5364ca89446f"
Template: "d91d3d2f-9c10-4e6e-9f5c-5364ca89446f"
Path: /sitecore/templates/TheAA/Settings/ProductBuilder/CoreProduct/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160603T143111Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b1161c9e-83e7-4b21-911f-6ea894341faf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160609T142745Z
    - ID: "e79341b0-67a2-4fbb-91cc-0de33c661ffa"
      Hint: ProductName
      Value: $name
