---
ID: "90fb31ee-65cd-41b3-8ce9-dcf5ea86406e"
Parent: "b4c89f3a-578f-4a59-a9c2-6eb188cf8434"
Template: "b4c89f3a-578f-4a59-a9c2-6eb188cf8434"
Path: /sitecore/templates/TheAA/Modules/ContactUsLink/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170118T142452Z
    - ID: "424768be-6019-43eb-a098-24c5429bec5e"
      Hint: Link
      Value: |
        <link text="$name" linktype="external" url="" anchor="" target="" />
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "13dd91d4-1cda-4924-971a-e4b4a03d2fd1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20170118T142510Z
