---
ID: "25c5b23e-3231-4c98-9089-ce7819b32fd0"
Parent: "6ec2fb6b-1773-4183-9db3-194048d0c286"
Template: "6ec2fb6b-1773-4183-9db3-194048d0c286"
Path: /sitecore/templates/TheAA/Settings/SalesJourney/Blocks/CoverageType/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160909T111654Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7da2d9e4-dd57-439c-bef5-d1ab2c98a23e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20160916T140636Z
