---
ID: "105c024a-aa9e-4e6b-a030-80ff491e8227"
Parent: "9e1e824e-9877-4ff3-bae4-ba35e3ae42e1"
Template: "9e1e824e-9877-4ff3-bae4-ba35e3ae42e1"
Path: /sitecore/templates/TheAA/Pages/HotelPage/__Standard Values
SharedFields:
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\AA Basic Editor|pe|-item:create|-item:write|-item:delete|-item:rename|pd|-item:create|-item:write|-item:delete|-item:rename|ar|sitecore\AA Advanced Editor|pe|-item:create|-item:write|-item:delete|-item:rename|pd|-item:create|-item:write|-item:delete|-item:rename|ar|sitecore\AA Approver|pe|-item:create|-item:write|-item:delete|-item:rename|pd|-item:create|-item:write|-item:delete|-item:rename|
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{D55D083A-7513-40E5-9E6A-A7B38DD97B9A}">
        <r
          id="{B9125386-572A-4E74-AFE1-B0CFF521E5D1}"
          ph="/metadata"
          uid="{97F4A3A2-E660-424F-B42F-1C7AD0508638}" />
        <r
          id="{194BD64B-175D-4760-A722-B11D61E94570}"
          ph="/metadata"
          uid="{E2233937-255C-452D-8485-7400B7A156B3}" />
        <r
          id="{1D5439DC-9410-4D11-8A9F-BEFC4645D64C}"
          ph="/metadata"
          uid="{E2CFEA98-FE77-460B-853F-3DE8A6A382ED}" />
        <r
          id="{CA4AD315-27CD-47B6-BEED-B0B97CE65FE7}"
          ph="/metadata"
          uid="{55756A11-0831-444A-AB5A-E8A48141B38A}" />
        <r
          ds=""
          id="{A167B31B-466E-496C-BA49-FD3696D06FA2}"
          par=""
          ph="/bodystart"
          uid="{C6BFBF73-88CD-4A60-BD6A-1A65E9369171}" />
        <r
          id="{1B770013-F801-4875-B19E-BB3881229045}"
          ph="/bodystart"
          uid="{9FFCF737-5B3F-4156-8812-1E7CA53B6B8A}" />
        <r
          ds=""
          id="{6525FA17-EE28-4A0C-AE02-6D2BAEF06ED2}"
          par=""
          ph="DISABLED/cookiebanner"
          uid="{EBDC1CE2-3E20-418E-808B-1E4EF754E162}" />
        <r
          id="{C582CB36-C5FC-45F8-AD34-D814B3B6187E}"
          par="test=foo"
          ph="/theaa"
          uid="{AFB59DDE-A881-4B86-A7D4-62EB32D155A7}" />
        <r
          ds="{CE20C138-928F-4D27-8EAE-C3ECE015A2FA}"
          id="{8712E3CB-A1B6-46AB-8367-A5D9581DA30A}"
          par=""
          ph="/theaa/hotelpage-r5/column-1"
          uid="{B005DE0D-8B3D-463C-A24D-A86BA891EB73}" />
        <r
          id="{8C485E7D-8B64-445A-9C8A-D1A3390AD370}"
          ph="/footer"
          uid="{DEF56108-A7BB-4262-B2E9-A1D964C3A599}" />
        <r
          id="{69C47E28-15B6-4770-A7EB-7F04B24B56D9}"
          ph="/theaa"
          uid="{23778377-7ED8-4EFF-A64D-FCE980B70DB9}" />
        <r
          id="{AC985DF8-F548-4E35-B486-5F484147427B}"
          ph="/theaa"
          uid="{027A6ED0-0B99-42ED-BE3F-CF9545629A9A}" />
        <r
          ds=""
          id="{E8DAA6AA-48A1-43E6-BB99-8647C2277848}"
          par="RowBackgroundStyle=%7B9A854E29-FA32-4CED-AAD2-75014F72E945%7D&amp;RowWidth=%7B1D6A3446-1420-4448-9568-82A6403039E9%7D"
          ph="hotelpage-r1"
          uid="{8FFB3609-679D-4ECF-B63A-50B832F26D53}" />
        <r
          ds=""
          id="{57BA48BE-5CBD-4C8A-A202-BC4691236FBD}"
          par="RowBackgroundStyle=%7B9A854E29-FA32-4CED-AAD2-75014F72E945%7D&amp;RowWidth=%7B1736ADBD-BFEC-4FC6-B098-D80E7EA74C38%7D"
          ph="hotelpage-r2"
          uid="{F5B7146C-E93B-4E27-955A-6ADE3A9561AC}" />
        <r
          ds=""
          id="{57BA48BE-5CBD-4C8A-A202-BC4691236FBD}"
          par="RowBackgroundStyle=%7B9A854E29-FA32-4CED-AAD2-75014F72E945%7D&amp;RowWidth=%7BE08388E2-BACA-4B4E-8AE4-54BB5EEB183B%7D"
          ph="hotelpage-r3"
          uid="{1C1D06A6-CF63-4026-8293-909E4920A282}" />
        <r
          ds=""
          id="{E8DAA6AA-48A1-43E6-BB99-8647C2277848}"
          par="RowBackgroundStyle=%7B9A854E29-FA32-4CED-AAD2-75014F72E945%7D&amp;RowWidth=%7BE08388E2-BACA-4B4E-8AE4-54BB5EEB183B%7D"
          ph="hotelpage-r4"
          uid="{8426D560-1A5A-4ED6-97BC-2099415EFE76}" />
        <r
          id="{E8DAA6AA-48A1-43E6-BB99-8647C2277848}"
          ph="hotelpage-r5"
          uid="{1FBA0C46-A22D-42BB-ADEB-B40DE91AC718}" />
        <r
          ds=""
          id="{4FA0A664-1A1E-4DB1-8AD2-4A6913B3EC7C}"
          par=""
          ph="/theaa/hotelpage-r1/column-1"
          uid="{B2B6D3CD-D31B-4F95-9F5C-63F140327935}" />
        <r
          ds=""
          id="{DA2F9899-9227-4284-8D91-55A5B4C47B46}"
          par=""
          ph="/theaa/hotelpage-r2/column-2"
          uid="{027AC55C-8E60-4720-8EE5-4BDEC8FDBC16}" />
        <r
          ds=""
          id="{C7FF5173-405B-42B6-88DB-C1DF6CB1D54F}"
          par=""
          ph="/theaa/hotelpage-r2/column-1"
          uid="{25B4F45F-88FB-4651-BA11-4A0425B09142}" />
        <r
          ds=""
          id="{7744E768-1C70-404A-A49D-4706BC9886B6}"
          par=""
          ph="/theaa/hotelpage-r2/column-1"
          uid="{725D81EC-070F-4A0A-B162-BCB58982E8A8}" />
        <r
          ds=""
          id="{CD6848A2-0FA1-404F-8004-840884060F6F}"
          par="ScreenName&amp;TwitterPostCount&amp;Width=%7BFDBF3B16-FEFB-4D43-A114-3BF594048E8E%7D"
          ph="/theaa/hotelpage-r2/column-2"
          uid="{48A6E5B1-22AD-4E28-80E3-4B62B8914240}" />
        <r
          ds=""
          id="{CBB8FB59-6F9C-4DE8-8305-F3105DB7BE91}"
          par=""
          ph="/theaa/hotelpage-r2/column-1"
          uid="{180E783A-095B-4ACC-A411-0100857528E9}" />
        <r
          ds=""
          id="{0FA72E5E-98F5-44CE-A7C9-ED99434EBAFD}"
          par=""
          ph="/theaa/hotelpage-r2/column-1"
          uid="{5C84BCC7-5735-4E60-ABFC-A81A45236A22}" />
        <r
          ds=""
          id="{CF8F6C22-D687-4374-8EA3-15DEB185B08F}"
          par=""
          ph="/theaa/hotelpage-r2/column-1"
          uid="{0BFB29C7-087D-4D30-A86A-DCB199DF49A9}" />
        <r
          ds=""
          id="{94A85E2E-8190-4468-9726-96DB010ED117}"
          par=""
          ph="/theaa/hotelpage-r2/column-1"
          uid="{7AB1F07D-B3E9-41C9-9BF3-73C75233832C}" />
        <r
          ds=""
          id="{3C293C3D-A3FE-4E09-A49C-B83B116E4D94}"
          par=""
          ph="/theaa/hotelpage-r2/column-1"
          uid="{7D17086E-961F-45D0-8AE2-D774A54A2E79}" />
        <r
          ds=""
          id="{2F0DEDCF-FBE9-4793-94A9-8F04338AEAE1}"
          par=""
          ph="/theaa/hotelpage-r3/column-1"
          uid="{C718DD37-308B-46D2-993D-43980EDA3C63}" />
        <r
          id="{238BA669-AEAC-47F6-B436-CAD468DD2E17}"
          ph="/theaa/hotelpage-r4/column-1"
          uid="{02EC6504-9E3F-4570-A3B5-4F9FE1E2F5B5}" />
        <r
          ds=""
          id="{923A0CAC-9569-4797-A0BC-2543EC318FAA}"
          par=""
          ph="/theaa/hotelpage-r4/column-1"
          uid="{5B27F8D4-92E4-4D5C-83D3-CBE19C8F994A}" />
        <r
          ds="{BA825EBB-3EF7-4396-9C18-4169399BC32A}"
          id="{24BD4DBF-B69A-4090-AE1C-4E6C24342DC4}"
          par="PodWidth=%7B67621776-375D-4EC9-8E38-84AD89F8E3BE%7D&amp;Styling=%7BD2B14D6C-8218-432B-86AC-6BE284975038%7D&amp;ContentAlignment=%7B182741F7-AC04-4196-8015-A930C7AB0D6F%7D&amp;TextColour=%7BC20A13D6-F8F6-4A3B-AD92-453E7538C5CE%7D&amp;ButtonStyles=%7B7B41EBD1-0D58-454E-A7EA-BD873E5A70ED%7D&amp;SecondaryButtonStyle=%7BC1F56865-76AA-46B8-A475-9F0A3633D8F6%7D"
          ph="/theaa/hotelpage-r3/column-2"
          uid="{86A2534B-E02C-45C7-8018-F8407B0FB4A7}" />
        <r
          id="{62150AB5-8424-485D-AB1F-050458C5AEED}"
          ph="/footer"
          uid="{B2A44659-FE4E-44C8-BC8F-83A86C30DB0D}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160812T160752Z
    - ID: "2e31f721-b2c7-4e9f-88d5-e87d34da261f"
      Hint: RemoveDefaultScripts
      Value: 
    - ID: "48737f24-10f6-4443-b2f0-04265a4647c0"
      Hint: TealiumProfileType
      Value: "{17CB4018-8409-4DFA-9476-767EE0857986}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "95559d08-a619-4a7b-ac45-2236c51f2ad8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230323T032630Z
