---
ID: "e6f6f7a8-0292-4c1d-bda5-cb330de35a19"
Parent: "54bb930c-7914-414c-b569-a122df26d999"
Template: "54bb930c-7914-414c-b569-a122df26d999"
Path: /sitecore/templates/TheAA/Pages/TestPage/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{D55D083A-7513-40E5-9E6A-A7B38DD97B9A}">
        <r
          id="{B9125386-572A-4E74-AFE1-B0CFF521E5D1}"
          ph="/metadata"
          uid="{97F4A3A2-E660-424F-B42F-1C7AD0508638}" />
        <r
          id="{1D5439DC-9410-4D11-8A9F-BEFC4645D64C}"
          ph="/metadata"
          uid="{6A62DB5D-BEFF-4D52-8273-F0A3BE1D5AB8}" />
        <r
          id="{CA4AD315-27CD-47B6-BEED-B0B97CE65FE7}"
          ph="/metadata"
          uid="{EF27EE6E-7B4B-442C-A157-0E3E5755B188}" />
        <r
          ds=""
          id="{A167B31B-466E-496C-BA49-FD3696D06FA2}"
          par=""
          ph="/bodystart"
          uid="{C6BFBF73-88CD-4A60-BD6A-1A65E9369171}" />
        <r
          id="{1B770013-F801-4875-B19E-BB3881229045}"
          ph="/bodystart"
          uid="{9FFCF737-5B3F-4156-8812-1E7CA53B6B8A}" />
        <r
          ds=""
          id="{6525FA17-EE28-4A0C-AE02-6D2BAEF06ED2}"
          par=""
          ph="DISABLED/cookiebanner"
          uid="{EBDC1CE2-3E20-418E-808B-1E4EF754E162}" />
        <r
          id="{C582CB36-C5FC-45F8-AD34-D814B3B6187E}"
          par=""
          ph="/theaa"
          uid="{AFB59DDE-A881-4B86-A7D4-62EB32D155A7}" />
        <r
          ds=""
          id="{36107EA8-F0FE-4B94-BCBA-A7E0AC8EF0FB}"
          par=""
          ph="/theaa"
          uid="{5A39E0C8-46A9-40BC-9AA0-5A111661C1F4}" />
        <r
          ds=""
          id="{E8DAA6AA-48A1-43E6-BB99-8647C2277848}"
          par="RowWidth=%7bE08388E2-BACA-4B4E-8AE4-54BB5EEB183B%7d&amp;Caching=0%7c0%7c0%7c0%7c0%7c0%7c0%7c0&amp;RowBackgroundStyle=%7b9A854E29-FA32-4CED-AAD2-75014F72E945%7d"
          ph="/theaa/blankpage-r1"
          uid="{355C8DC3-C0D9-4AA4-8FAC-9412C81C1855}" />
        <r
          ds=""
          id="{8C485E7D-8B64-445A-9C8A-D1A3390AD370}"
          par=""
          ph="/footer"
          uid="{9F0A1706-471B-422B-8A91-DFDB64127C33}" />
        <r
          id="{69C47E28-15B6-4770-A7EB-7F04B24B56D9}"
          ph="/theaa"
          uid="{23778377-7ED8-4EFF-A64D-FCE980B70DB9}" />
        <r
          id="{62150AB5-8424-485D-AB1F-050458C5AEED}"
          ph="/footer"
          uid="{B2A44659-FE4E-44C8-BC8F-83A86C30DB0D}" />
        <r
          id="{194BD64B-175D-4760-A722-B11D61E94570}"
          ph="/metadata"
          uid="{E2233937-255C-452D-8485-7400B7A156B3}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1"></r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151214T115205Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d7b8f944-46fd-4ddb-9c09-40d36a4f4807"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230323T032627Z
  - Version: 2
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{BB46309D-349C-4A37-A517-386A917196ED}">
              <p:d />
            </r>
            <r
              uid="{E070B524-177B-4631-8A99-A96D79D04B78}"
              p:after="*[1=2]"
              s:ds=""
              s:id="{22DDED64-9C82-4A2B-9D38-E8798AEACF8B}"
              s:par=""
              s:ph="/metadata" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151214T115205Z
    - ID: "2e31f721-b2c7-4e9f-88d5-e87d34da261f"
      Hint: RemoveDefaultScripts
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "52fe2598-1381-43d3-a10c-5ce15ba9149c"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230323T032627Z
