---
ID: "534e622c-448a-471d-bbb8-9ac8a711d13e"
Parent: "ea15a8bb-c688-4565-9ecb-48da1bea5fb6"
Template: "ea15a8bb-c688-4565-9ecb-48da1bea5fb6"
Path: /sitecore/templates/Feature/AA/Basic Content/Jump Link List/Jump Link List Setting/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240816T084339Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "acb917fd-6dbe-4314-bda6-99effa2bbbea"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        theaa\Anonymous
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241010T020457Z
