trigger: none

resources:
  repositories:
  - repository: aa-web-dev
    type: git
    name: aa-web
    ref: 'refs/heads/develop'
  - repository: aa-web-uat
    type: git
    name: aa-web
    ref: 'refs/heads/uat'
  - repository: aa-web-production
    type: git
    name: aa-web
    ref: 'refs/heads/production'

stages:
- stage: DeployToDevelopment
  jobs:
  - deployment: DeployToDevelopment
    displayName: "Deploy to Development - Vercel"
    environment: 'Development'
    workspace:
      clean: all
    pool:
      vmImage: 'windows-latest'
    variables:
    - name: sitecore_environment
      value: development
    - group: 'Release Pipeline Variables Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: 'aa-web-dev'
          - template: 'azure-pipeline-step-deploy-vercel.yml'